[phases.setup]
nixPkgs = ["nodejs_18", "pnpm-9_x", "openssl"]

[phases.install]
cmds = [
  "npm install -g corepack@0.24.1 && corepack enable",
  "pnpm i --frozen-lockfile"
]

[phases.build]
cmds = [
  "pnpm build:all"
]

[start]
cmd = "pnpm start"

# Note: This builds all services. Override the start command in Railway settings:
# - Sentryvibe service: pnpm start (or pnpm --filter sentryvibe start)
# - Broker service: pnpm start:broker (or pnpm --filter sentryvibe-broker start)
