packages:
  - apps/openbuilder
  - apps/runner
  - apps/opencode-service
  - packages/agent-core
  - packages/opencode-client
  # packages/runner - disabled for now, needs proper cross-package bundling setup
