[phases.setup]
nixPkgs = ["nodejs_18", "pnpm-9_x", "openssl"]


[phases.install]
cmds = ["pnpm install --frozen-lockfile --filter=sentryvibe-broker..."]

[phases.build]
cmds = ["pnpm --filter=sentryvibe-broker run build"]

[start]
cmd = "pnpm --filter=sentryvibe-broker start"
