[build]
builder = "DOCKERFILE"
# Use root-level Dockerfile.broker for monorepo compatibility
# This Dockerfile must be built from repository root
dockerfilePath = "Dockerfile.broker"

[deploy]
startCommand = "node dist/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
