[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = [
  "ls -la",
  "cat pnpm-workspace.yaml",
  "pnpm install"
]

[phases.build]
cmds = [
  "pnpm --filter @sentryvibe/agent-core build",
  "pnpm --filter sentryvibe build"
]

[start]
cmd = "pnpm --filter sentryvibe start"
