[phases.setup]
nixPkgs = ["nodejs_18", "pnpm-9_x", "openssl"]

[phases.install]
cmds = [
  "npm install -g corepack@0.24.1 && corepack enable",
  "pnpm i --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm install && pnpm --filter @sentryvibe/agent-core build && pnpm --filter sentryvibe build"]

[start]
cmd = "pnpm start"
