[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["pnpm install --filter=sentryvibe..."]

[phases.build]
cmds = ["pnpm --filter=sentryvibe run build"]

[start]
cmd = "pnpm --filter=sentryvibe start"
