import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ProjectProvider } from "@/contexts/ProjectContext";

const dammitSans = localFont({
  src: "../../public/dammitsansv0.2-bold.otf",
  variable: "--font-dammit-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dammitSans.variable} antialiased`}
      >
        <ProjectProvider>
          {children}
        </ProjectProvider>
      </body>
    </html>
  );
}
